import EditOutlinedIcon from '@mui/icons-material/EditOutlined';
import ExpandMoreOutlinedIcon from '@mui/icons-material/ExpandMoreOutlined';
import CloseOutlinedIcon from '@mui/icons-material/CloseOutlined';
import DeleteOutlineOutlinedIcon from '@mui/icons-material/DeleteOutlineOutlined';
import DoneOutlinedIcon from '@mui/icons-material/DoneOutlined';
import AddOutlinedIcon from '@mui/icons-material/AddOutlined';
import PrintOutlinedIcon from '@mui/icons-material/PrintOutlined';
import MenuOutlinedIcon from '@mui/icons-material/MenuOutlined';
import IndeterminateCheckBoxOutlinedIcon from '@mui/icons-material/IndeterminateCheckBoxOutlined';
import LibraryAddCheckOutlinedIcon from '@mui/icons-material/LibraryAddCheckOutlined';
import MoreVertOutlinedIcon from '@mui/icons-material/MoreVertOutlined';
import DifferenceOutlinedIcon from '@mui/icons-material/DifferenceOutlined';
import CheckBoxOutlineBlankOutlinedIcon from '@mui/icons-material/CheckBoxOutlineBlankOutlined';
import CheckBoxOutlinedIcon from '@mui/icons-material/CheckBoxOutlined';
import InfoOutlinedIcon from '@mui/icons-material/InfoOutlined';
import TranslateOutlinedIcon from '@mui/icons-material/TranslateOutlined';

export const EditIcon = EditOutlinedIcon;
export const ExpandMoreIcon = ExpandMoreOutlinedIcon;
export const CloseIcon = CloseOutlinedIcon;
export const DeleteIcon = DeleteOutlineOutlinedIcon;
export const DoneIcon = DoneOutlinedIcon;
export const AddIcon = AddOutlinedIcon;
export const PrintIcon = PrintOutlinedIcon;
export const MenuIcon = MenuOutlinedIcon;
export const ClearAllCheckboxIcon = IndeterminateCheckBoxOutlinedIcon;
export const CheckAllCheckboxIcon = LibraryAddCheckOutlinedIcon;
export const MoreVertIcon = MoreVertOutlinedIcon;
export const CopyOfIcon = DifferenceOutlinedIcon;

export const CheckedIcon = CheckBoxOutlinedIcon;
export const UnCheckedIcon = CheckBoxOutlineBlankOutlinedIcon;
export const InfoIcon = InfoOutlinedIcon;
export const LanguageIcon = TranslateOutlinedIcon;
